In [2]:
-- Sales
CREATE TABLE Sales(
    SalesID INTEGER PRIMARY KEY,
    ProductID INTEGER,
    QuantitySold INTEGER,
    DateSold TEXT,
    SalespersonID INTEGER
);

-- Marketing
CREATE TABLE Marketing (
    CampaignID INTEGER PRIMARY KEY,
    CampaignName TEXT,
    StartDate TEXT,
    EndDate TEXT,
    Budget REAL,
    MarketingManagerID INTEGER,
    Channel TEXT,
    TargetAudience TEXT
);

-- Shipping
CREATE TABLE Shipping (
    ShippingID INTEGER PRIMARY KEY,
    OrderID INTEGER,
    ShipDate TEXT,
    ShipperName TEXT,
    TrackingNumber TEXT,
    ShippingCost REAL,
    EstimatedDeliveryDate TEXT
);

-- ReceivingOrders
CREATE TABLE ReceivingOrders (
    OrderID INTEGER PRIMARY KEY,
    ProductID INTEGER,
    QuantityReceived INTEGER,
    ReceiveDate TEXT,
    ReceiverID INTEGER,
    SupplierID INTEGER,
    Cost REAL
);

-- Managers
CREATE TABLE Managers (
    ManagerID INTEGER PRIMARY KEY,
    FirstName TEXT,
    LastName TEXT,
    Email TEXT,
    Department TEXT,
    HireDate TEXT,
    Salary REAL,
    ReportsTo INTEGER
);

-- ITDepartment
CREATE TABLE ITDepartment (
    ITMemberID INTEGER PRIMARY KEY,
    FirstName TEXT,
    LastName TEXT,
    Email TEXT,
    Role TEXT,
    ManagerID INTEGER,
    HireDate TEXT,
    Salary REAL
);

-- KPIs
CREATE TABLE KPIs (
    KPIID INTEGER PRIMARY KEY,
    KPIName TEXT,
    Value REAL,
    DateMeasured TEXT,
    Department TEXT,
    Goal REAL,
    Frequency TEXT
);

-- Additional Tables
-- Products
CREATE TABLE Products (
    ProductID INTEGER PRIMARY KEY,
    ProductName TEXT,
    Price REAL,
    Category TEXT,
    Stock INTEGER
);

-- Employees
CREATE TABLE Employees (
    EmployeeID INTEGER PRIMARY KEY,
    FirstName TEXT,
    LastName TEXT,
    Email TEXT,
    Department TEXT,
    HireDate TEXT,
    Salary REAL,
    ManagerID INTEGER
);

-- Orders
CREATE TABLE Orders (
    OrderID INTEGER PRIMARY KEY,
    CustomerID INTEGER,
    DatePlaced TEXT,
    Total REAL,
    Status TEXT
);

-- Suppliers
CREATE TABLE Suppliers (
    SupplierID INTEGER PRIMARY KEY,
    SupplierName TEXT,
    ContactName TEXT,
    ContactEmail TEXT,
    Address TEXT,
    City TEXT,
    Country TEXT,
    Phone TEXT
);

-- Customers
CREATE TABLE Customers (
    CustomerID INTEGER PRIMARY KEY,
    FirstName TEXT,
    LastName TEXT,
    Email TEXT,
    Phone TEXT,
    Address TEXT,
    City TEXT,
    Country TEXT
);

SyntaxError: ignored